import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanStackProvider from "@/providers/TanStackProvider";
import Navbar from "@/components/Navbar";
import SearchBox from "@/components/SearchBox";
import { UnitButton } from "@/components/UnitButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className} >
        <TanStackProvider>
          <div className='bg-gray-100 '>
            <Navbar/>
            <section className="block md:hidden pt-10">
              <SearchBox/>
            </section>
            <div className='flex flex-col justify-end w-full items-center'>
              <UnitButton/>
            </div>
            {children}
          </div>
        </TanStackProvider>
      </body>
    </html>
  );
}
